controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Tasks;
use app\models\TasksSearch;
use Yii;
use yii\db\StaleObjectException;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new TasksSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->get());
        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionInsert()
    {
        $model = new Tasks();
        if ($model->load(Yii::$app->request->post())) {
            $model->created_at = time();
            $model->updated_at = time();
            $model->save();
            return $this->redirect(['/']);
        } else {
            return $this->renderAjax('insert', ['model' => $model]);
        }
    }

    public function actionUpdate($id)
    {
        $model = Tasks::findOne($id);
        try {
            if ($model->load(Yii::$app->request->post())) {
                $model->updated_at = time();
                if ($model->save()) {
                    Yii::$app->session->setFlash('success', 'Record updated successfully.');
                } else {
                    Yii::$app->session->setFlash('error', 'Failed to update record.');
                }
                return $this->redirect(['/']);
            }
        } catch (StaleObjectException $e) {
            Yii::$app->session->setFlash('error', 'Record has been modified by another user. Please reload the record and try again.');
            return $this->redirect(['/']);
        }
        return $this->renderAjax('update', ['model' => $model]);
    }
}

views/site/error.php
<?php

/** @var yii\web\View $this */
/** @var string $name */
/** @var string $message */
/** @var Exception$exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/** @var yii\web\View $this */

use yii\helpers\Url;
use yii\grid\GridView;
use yii\helpers\Html;
use yii\bootstrap4\Modal;

?>

<h1>TO DO APP</h1>

<?= GridView::widget([
    'dataProvider' => $dataProvider,
    'summary' => false,
    'pager' => [
        'options' => [
            'tag' => 'ul',
            'class' => 'pagination pagination-sm',
        ]
    ],
    'columns' => [
        [
            'attribute' => 'header',
            'value' => function ($data) {
                return "<span class='grid-cell-gray'>" . $data->header . "</span>";
            },
            'format' => 'html',
            'filter' => false
        ],
        [
            'attribute' => 'priority',
            'value' => function ($data) {
                switch ($data->priority) {
                    case 1:
                        $priority = 'низкий';
                        break;
                    case 2:
                        $priority = 'средний';
                        break;
                    case 3:
                        $priority = 'высокий';
                        break;
                }
                return $priority;
            },
            'filter' => false
        ],
        [
            'attribute' => 'status',
            'value' => function ($data) {
                switch ($data->status) {
                    case 0:
                        $status = 'к выполнению';
                        break;
                    case 1:
                        $status = 'выполнена';
                        break;
                    default:
                        $status = 'к выполнению';
                        break;
                }
                return $status;
            },
            'filter' => false
        ],
        [
            'label' => 'Действия',
            'format' => 'raw',
            'value' => function ($data) {
                return Html::button(
                    "Редактировать",
                    [
                        'value' => Url::to("/site/update?id=$data->id"),
                        'id' => 'modalButtonUpdate' . $data->id,
                        'class' => 'btn btn-primary not-button'
                    ]
                );
            }
        ],
    ],
]); ?>

<?php
Modal::begin([
    'id' => 'modalUpdate',
    'size' => 'modal-lg'
]);
echo "<div id='modalContent1'></div>";
Modal::end();
?>

<?=
Html::button("Новая задача", ['value' => Url::to('/site/insert'), 'class' => 'btn btn-primary', 'id' => 'modalButton'])
?>
<?php
Modal::begin([
    'id' => 'modal',
    'size' => 'modal-lg'
]);
echo "<div id='modalContent'></div>";
Modal::end();
?>

views/site/insert.php
<?php
/* @var $this yii\web\View */

use yii\widgets\ActiveForm;
use yii\helpers\Html;

$this->title = 'Добавить задачу';

?>

<div id='modalContent'>
    <div class="page-feedback">
        <h1><?= Html::encode($this->title) ?></h1>

        <?php $form = ActiveForm::begin(); ?>
        <?= $form->field($model, 'header')->input('string', ['required' => '']); ?>

        <?= $form->field($model, 'priority')->dropDownList(
            [
                '1' => 'низкий',
                '2' => 'средний',
                '3' => 'высокий'
            ]
        )
        ?>
        <?= $form->field($model, 'status')->checkbox(
            [
                'checked' => false
            ]
        ); ?>

        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary']); ?>
        <?php ActiveForm::end(); ?>
    </div>
</div>

views/site/update.php
<?php
/* @var $this yii\web\View */

use yii\bootstrap4\ActiveForm;
use yii\helpers\Html;

?>

<div>
    <h1><?= Html::encode('Редактировать задачу') ?></h1>


    <?php $form = ActiveForm::begin(); ?>
    <?= $form->field($model, 'header')->input('string', ['required' => '']); ?>

    <?= $form->field($model, 'priority')->dropDownList(
        [
            '1' => 'низкий',
            '2' => 'средний',
            '3' => 'высокий'
        ]
    )
    ?>
    <?= $form->field($model, 'status')->checkbox()->label('Готово'); ?>
    <?= $form->field($model, 'version')->hiddenInput()->label(false); ?>
    <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary']); ?>
    <?php ActiveForm::end(); ?>
</div>